services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      NODE_ENV: development
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - strapi_pg_data:/var/lib/postgresql/data

volumes:
  strapi_pg_data: